{{- range $namespace, $ns := .Values.namespaces }}
{{- if $ns.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  labels:
    name: {{ $namespace }}
    tier: {{ $ns.tier }}
    environment: {{ $.Values.global.environment }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: erp-uno
    meta.helm.sh/release-namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $namespace }}-sa
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: erp-uno
    meta.helm.sh/release-namespace: default
{{- end }}
{{- end }}
