apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-pki-data
  namespace: erp-security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-directory-data
  namespace: erp-security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
