apiVersion: v2
name: erp-uno
description: "ERP/1: Підприємство"
type: application
version: 2024.6.15
appVersion: "2024.6.15"
keywords:
  - beam
  - kubernetes
  - gitops
maintainers:
  - name: Zen Crypted
